name: Prebuilt repo + Snyk Security Scanning (OS)

# Runs a single Snyk Products (Open Source)
# Snyk installation via npm
# Node.js version: 18.4

# Prerequisites:
# - Set a SNYK_TOKEN and a SNYK_ORG in the pipelines secrets

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js for installing Snyk 
      uses: actions/setup-node@v4
      with:
        node-version: 18.4

    # Install jq for snyk-filter. This is only for completeness, as GH actions runner already contain it.
    - run: sudo apt-get install jq

    # Install & prepare Snyk
    - run: npm install --location=global snyk snyk-filter
    
    # Authenticate the Snyk instance
    - run: snyk auth ${{ secrets.SNYK_TOKEN }}

    # Perform a monitor. This will NOT cause failures.
    - name: Snyk Open Source Scan
      run: snyk monitor --org=${{ secrets.SNYK_ORG }}
      continue-on-error: true

    # Perform a simple test and apply snyk-filter
    - name: Snyk Open Source Scan, filtered by snyk-filter
      run: snyk test --json | snyk-filter